-- Purge des tables dans l'ordre inverse des dépendances
TRUNCATE TABLE history RESTART IDENTITY CASCADE;

TRUNCATE TABLE advertisements RESTART IDENTITY CASCADE;

TRUNCATE TABLE companies RESTART IDENTITY CASCADE;

TRUNCATE TABLE users RESTART IDENTITY CASCADE;
